/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 
 -------------- celery@airdrop-me.home v5.3.1 (emerald-rush)
--- ***** ----- 
-- ******* ---- macOS-13.4.1-arm64-arm-64bit 2023-08-01 12:24:46
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tarkhees:0x103f616a0
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . appointments.tasks.send_reminder_email
  . appointments.tasks.send_reminder_email_task
  . appointments.tasks.send_reminder_sms
  . appointments.tasks.send_reminder_sms_task

[2023-08-01 12:24:46,880: WARNING/MainProcess] /Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-08-01 12:24:46,986: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2023-08-01 12:24:46,987: WARNING/MainProcess] /Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-08-01 12:24:46,994: INFO/MainProcess] mingle: searching for neighbors
[2023-08-01 12:24:48,019: INFO/MainProcess] mingle: all alone
[2023-08-01 12:24:48,042: INFO/MainProcess] celery@airdrop-me.home ready.
[2023-08-01 12:24:48,044: INFO/MainProcess] Task appointments.tasks.send_reminder_email_task[1af34dbe-76f0-4550-b313-0fe862dd27f2] received
[2023-08-01 12:24:48,045: INFO/MainProcess] Task appointments.tasks.send_reminder_email_task[71a4145e-839b-498c-a9a8-efd24b595988] received
[2023-08-01 12:25:19,367: INFO/MainProcess] Task appointments.tasks.send_reminder_email_task[dad3be11-8742-4342-accd-08c96bdf0521] received
[2023-08-01 12:26:35,466: INFO/MainProcess] Task appointments.tasks.send_reminder_email_task[06380368-536e-41e2-8f30-c35f685e0b4f] received
[2023-08-01 12:50:19,484: INFO/MainProcess] Task appointments.tasks.send_reminder_email_task[3f764942-7138-4f77-99a1-213d3c6ed84a] received

SIGHUP not supported: Restarting with SIGHUP is unstable on this platform!
[2023-08-01 12:53:34,231: ERROR/MainProcess] Process 'ForkPoolWorker-8' pid:31696 exited with 'exitcode 70'
[2023-08-01 12:53:34,243: ERROR/MainProcess] Process 'ForkPoolWorker-7' pid:31695 exited with 'exitcode 70'
[2023-08-01 12:53:34,255: ERROR/MainProcess] Process 'ForkPoolWorker-6' pid:31694 exited with 'exitcode 70'
[2023-08-01 12:53:34,266: ERROR/MainProcess] Process 'ForkPoolWorker-3' pid:31689 exited with 'exitcode 70'
[2023-08-01 12:53:34,278: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:31688 exited with 'exitcode 70'
[2023-08-01 12:53:34,289: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:31687 exited with 'exitcode 70'
[2023-08-01 12:53:34,494: ERROR/MainProcess] Process 'ForkPoolWorker-5' pid:31693 exited with 'exitcode 70'
[2023-08-01 12:53:34,506: ERROR/MainProcess] Process 'ForkPoolWorker-4' pid:31691 exited with 'exitcode 70'
[2023-08-01 12:55:30,062: CRITICAL/MainProcess] Unrecoverable error: PreconditionFailed(406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more', (0, 0), '')
Traceback (most recent call last):
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 336, in start
    blueprint.start(self)
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 726, in start
    c.loop(*c.loop_args())
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/kombu/transport/base.py", line 248, in on_readable
    reader(loop)
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/kombu/transport/base.py", line 230, in _read
    drain_events(timeout=0)
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/amqp/connection.py", line 525, in drain_events
    while not self.blocking_read(timeout):
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/amqp/connection.py", line 531, in blocking_read
    return self.on_inbound_frame(frame)
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/amqp/method_framing.py", line 53, in on_frame
    callback(channel, method_sig, buf, None)
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/amqp/connection.py", line 537, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/amqp/abstract_channel.py", line 156, in dispatch_method
    listener(*args)
  File "/Users/harethhmoud/Desktop/Desktop - Hareths MacBook Pro/Everything/Personal/Projects/DMV/venv/lib/python3.9/site-packages/amqp/channel.py", line 293, in _on_close
    raise error_for_code(
amqp.exceptions.PreconditionFailed: (0, 0): (406) PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more
